version: "3.9"

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./html:/var/www/html
      - ./certs:/etc/nginx/certs
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "443:443"
    depends_on:
      - vlc_stream1
      - vlc_stream2

  vlc_stream1:
    container_name: vlc_stream1
    build:
      context: .
      dockerfile: Dockerfile.vlc
    restart: unless-stopped
    environment:
      - RTSP_URL=rtsp://admin:senha@192.168.1.2/Streaming/Channels/102
      - STREAM_PORT=8080
    ports:
      - "8001:8080"

  vlc_stream2:
    container_name: vlc_stream2
    build:
      context: .
      dockerfile: Dockerfile.vlc
    restart: unless-stopped
    environment:
      - RTSP_URL=rtsp://admin:senha@192.168.1.3/Streaming/Channels/102
      - STREAM_PORT=8080
    ports:
      - "8002:8080"

  watchdog:
    build:
      context: .
      dockerfile: Dockerfile.watchdog
    container_name: watchdog
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - vlc_stream1
      - vlc_stream2
